### ISSUE TITLE
Farmer v0.1 - Re-written in Golang

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#16]
We've decided to re-write Farmer completely in Golang, and release our first stable version.

## Glossary:
**Box** is a bunch of containers linked together which is an instance of your project with **a unique name**. It can be a test/staging instance and even a real production one.

## v0.1 Checklist
- [x] **Box** package which is the heart of Farmer whose responsibility is to:
  - [X] **Create** a box with its related container with a unique name, with a cloned source code; ready for deployment.
  - [X] **Delete** containers, volumes, backups, etc; of a box, by providing its name.
  - [X]  **Inspect** a box's containers information including container id, current ports, volumes, domains and etc; by providing box's name.
  - [X]  **Deploy** a box's containers information including container id, current ports, volumes, domains and etc; by providing box's name.
  - [X]  **List** retrieves list of all boxes with some basic information such as current ports, volumes, domains and etc.
- [X] **Docker API Client** wrapper, so that *Container* can talk to Docker Engine.
- [X] **Hub** package, so that we can send outputs to the user.
 - [X] Add a consumer user named `farmer` and monitoring access, for clients. (#36)
- [X] **Controller** package which is responsible for providing farmer's API for box management, domain management, authentication, etc. 
- [X] **Domain** (#19) package, which manages box's domains together with its underlying reverse-proxy.
- [x] **Installation script** (#18) which automates installation of Farmer and its dependencies. 
 - [X] Setup a RabbitMQ container for Hub
 - [X] Setup a MySql container for database
 - [X] Setup an Nginx container to be used as reverse-proxy for handling domains.
 - [x] Setup a Golang container for compiling and running Farmer server.
 - [x] Final tests.
- [x] Automatically download the Docker image defined in `.farmer.yml` if it's not locally available.

Your suggestions are very much appreciated :)

**Comment by aramalipoor** [comment]
v0.1 is out successfully. Thanks @majidgolshadi
